"""add mpesa transaction tracking fields

Revision ID: ce1fbd093df7
Revises: 03257fbce917
Create Date: 2026-08-10 12:38:26.997378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce1fbd093df7'
down_revision = '03257fbce917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_request_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('result_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('result_description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('mpesa_receipt_number', sa.String(length=100), nullable=True))

    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('mpesa_receipt_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('originator_conversation_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('result_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('result_description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.drop_column('result_description')
        batch_op.drop_column('result_code')
        batch_op.drop_column('originator_conversation_id')
        batch_op.drop_column('mpesa_receipt_number')
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('mpesa_receipt_number')
        batch_op.drop_column('result_description')
        batch_op.drop_column('result_code')
        batch_op.drop_column('checkout_request_id')
        batch_op.drop_column('merchant_request_id')

    # ### end Alembic commands ###
