"""link technicians to professions

Revision ID: e2e1bbeb06f2
Revises: 1bc0545f813f
Create Date: 2026-08-14 13:09:06.927263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e1bbeb06f2'
down_revision = '1bc0545f813f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technician_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profession_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_technician_profiles_profession_id', 'professions', ['profession_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technician_profiles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_technician_profiles_profession_id', type_='foreignkey')
        batch_op.drop_column('profession_id')

    # ### end Alembic commands ###
